main/urls.py
from django.urls import path,include,re_path
from main import views
app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/',views.user_signup,name="signup"),
    path('movies/', views.movies.as_view(), name='movies'),
    path('search/', views.search, name='search'),
    re_path(r'^accounts/(?P<pk>\d+)/(?P<user>\w+)/',views.account.as_view(),name="accounts"),
    re_path(r'^accounts-update/(?P<pk>\d+)/',views.account_update.as_view(),name="accounts-update"),
    re_path(r'^accounts-delete/(?P<pk>\d+)/',views.account_delete.as_view(),name="accounts-delete"),
    re_path(r'^movie-detail/(?P<pk>\d+)/',views.movie_detail_view.as_view(),name="movie-detail-view"),
    re_path(r'^theatre-list/(?P<pk>\d+)/',views.movie_booking_theatre.as_view(),name="movie-booking-theatre"),
    re_path(r'^booking/(?P<pk>\d+)/',views.show_details.as_view(),name="movie-booking"),
    # re_path(r'^booking/(?P<pk>\d+)/',views.booking,name="booking"),
    re_path(r'^book-ticket/(?P<pk>\d+)/(?P<id>\d+)',views.book_ticket,name="book-ticket"),
    re_path(r'^booked/(?P<pk>\d+)/',views.booked.as_view(),name="booked"),
    re_path(r'^cancel/(?P<pk>\d+)/',views.cancel_ticket,name="cancel_ticket"),
]

pct/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'),name='main'),
    path('manager/',include('login.urls'),name='manager'),
    path('manager/dashboard/',include('dashboard.urls'),name='dashboard'),
    path('accounts/', include('django.contrib.auth.urls'),name='auth'),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.forms import ModelForm
from dashboard.models import show
from django.contrib.auth.models import User

# Create your models here.


TICKET_STATUS_CHOICES = (
    (1, 'AVAILABLE'),
    (2, 'BLOCKED'),
    (3, 'BOOKED')
)

class booking(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField(null=False)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)
    row_num = models.PositiveSmallIntegerField(null=False, blank=False)
    col_num = models.PositiveSmallIntegerField(null=False, blank=False)
    show = models.ForeignKey(show,related_name="booking_show",null=False,on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name="booking_user",null=False,default=None, on_delete=models.CASCADE)
    status = models.IntegerField(choices=TICKET_STATUS_CHOICES, default=1)
    session = models.CharField(blank=False, null=False, max_length=200)

    class Meta:
        unique_together = ('show', 'row_num', 'col_num')


class TicketsForm(ModelForm):
    class Meta:
        model = booking
        fields = ['name','age','row_num', 'col_num',]

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseForbidden,HttpResponseRedirect,HttpResponseBadRequest
from dashboard import models
from dashboard.models import movie,show,theatre,screen,User
from django.views.generic import DetailView,ListView,TemplateView,UpdateView,DeleteView
from django.db import connection
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.db.models import Q
from django.contrib import messages
from main.models import TicketsForm,booking
from datetime import datetime, timedelta
from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request) :

    slider_images = movie.objects.raw('SELECT id,slideshow_image FROM dashboard_movie ORDER BY id DESC LIMIT 4')

    thumbnail_images = movie.objects.raw('SELECT id,thumbnail_image FROM dashboard_movie ORDER BY id DESC LIMIT 8')

    trailer = movie.objects.raw('SELECT id,trailer FROM dashboard_movie ORDER BY id DESC LIMIT 6')

    return render(request,'main/index.html',{ 'slider_images':slider_images,'thumbnail_images' : thumbnail_images,'trailer' : trailer })

class movies(ListView) :
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-view.html'

class movie_detail_view(DetailView) :
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-detail-view.html'

class movie_booking_theatre(DetailView) :
    context_object_name = 'movie'
    model = models.movie
    template_name = 'main/movie-booking-theatre.html'


class show_details(LoginRequiredMixin,DetailView) :

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    
        context['form'] = TicketsForm
        show_id = self.kwargs['pk']
        Show = show.objects.get(pk=show_id)
        context['tickets_booked'] = booking.objects.filter(show=Show)
        return context

    context_object_name = 'show'
    model = models.show
    template_name = 'main/booking-page.html'

@login_required
def book_ticket(request,pk=None,id=None):
   
    data = TicketsForm(request.POST)
    Booking = data.save(commit=False) 
    Show = show.objects.get(pk=pk)
    user = User.objects.get(pk=id)
    Booking.show = Show
    Booking.user = user

    if Booking.row_num == 0 or Booking.col_num == 0 
    or Booking.row_num > Show.screen.no_of_rows or Booking.col_num > Show.screen.no_of_columns:
        return HttpResponseBadRequest("Invalid ticket number")

    if not request.session.session_key:
        request.session.save()
    Booking.session = request.session.session_key 

    try:
        existing_tix = booking.objects.get(row_num=Booking.row_num, col_num=Booking.col_num, show=Show)
        if existing_tix.session == Booking.session and existing_tix.status == 1:
            if existing_tix.status == 1:
                existing_tix.delete()
            else:
                Booking = existing_tix
        else:
            return HttpResponseBadRequest("This ticket has already been reserved")
    except booking.DoesNotExist:
        pass

    Booking.save()
    return redirect('main:booked',pk=pk)


class account(LoginRequiredMixin,DetailView) :
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs['pk']
        username = self.kwargs['user']
        u = User.objects.get(pk=user_id)
        context['tickets_booked'] = booking.objects.filter(user=u)
        if u.username == username :
            context['test'] = username
            return context
    context_object_name = 'user'
    model = models.User
    template_name = 'main/account.html'


class account_update(LoginRequiredMixin,UpdateView) :
    context_object_name = 'user'
    model = models.User
    fields = ['username','first_name','last_name','email',]
    template_name = 'main/account_form.html'
    success_url = reverse_lazy('main:index')

class account_delete(LoginRequiredMixin,DeleteView) :
    context_object_name = 'user'
    model = models.User
    template_name = 'main/user_confirm_delete.html'
    success_url = reverse_lazy('main:index')

def user_signup(request) :
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid() : 
            user = form.save()
            return redirect('main:index')
    else :
        form = UserCreationForm()
    return render(request,'main/signup.html',{'form':form})


def search(request) :
    if request.method == 'POST' :
        search_query = request.POST['search']

        if search_query :
            result = movie.objects.filter(Q(name__icontains=search_query) | Q(hero__icontains=search_query) | Q(heroine__icontains=search_query))

            if result :
                return render(request,'main/search.html',{'results':result,'search_query' : search_query})
            else :
                messages.error(request,'Sorry no results found')
        else :
            return HttpResponseRedirect('/')

    return render(request,'main/search.html')

class booked(LoginRequiredMixin,DetailView) :
    context_object_name = 'show'
    model = models.show
    template_name = 'main/confirm_movie.html'


def cancel_ticket(request,pk=None) :
    Ticket = booking.objects.get(pk=pk)
    Ticket.delete()
    return redirect('main:index')
   





        

main/templates/main/account.html
{% extends 'main/layout.html' %}

{% load static %}

{% block content %}

{% if test %}
<style>

.btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-danger {
        font-weight: 700;
        border-radius: 2rem;
        width: 150px;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

    button:focus {
        outline: none !important;
    }

    h4 {
        letter-spacing: 3px;
        line-height : 32px;
        font-size: 18px;
    }



</style>



<div class="container">
    <a href="#profile"><button class="btn btn-primary">Profile</button></a>
    <a href="{% url 'main:accounts-update' pk=user.id %}"><button class="btn btn-primary">Edit Profile</button></a>
    <a href="{% url 'password_change' %}"><button  class="btn btn-primary">Password Change</button></a>
    <a href="{% url 'main:accounts-delete' pk=user.id %}"><button class="btn btn-danger">Delete Profile</button></a>
</div>

<div class="container" id="profile" style="margin-top: 40px;margin-bottom: 30px;">
    <h4>User Name : <strong>{{ user.username }}</strong></h4>
    <h4>First Name : <strong>{{ user.first_name }}</strong></h4>
    <h4>Last Name : <strong>{{ user.last_name }}</strong></h4>
    <h4>Email : <strong>{{ user.email }}</strong></h4>
    <h4>Active Status : <strong>{{ user.is_active }}</strong></h4>
    <h4>Date Joined : <strong>{{ user.date_joined }}</strong></h4>
    <h4>Last Login : <strong>{{ user.last_login }}</strong></h4>  
</div>


<div class="container">
    <h3><strong>Booked Tickets</strong></h3></br>
        <table class="table table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Created At</th>
                    <th>Movie</th>
                    <th>Theatre</th>
                    <th>Row No</th>
                    <th>Col No</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {% for t in tickets_booked %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ t.created_at }}</td>
                    <td>{{ t.show.movie.name }}</td>
                    <td>{{ t.show.theatre.name }}</td>
                    <td>{{ t.row_num }}</td>
                    <td>{{ t.col_num }}</td>
                    <td><a href="{% url 'main:cancel_ticket' pk=t.id  %}"><button class="btn btn-danger" style="width:70px;"> <i class="fas fa-times-circle"></i></button></a></td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
</div>


{% else %}

<div class="container" style="margin-top : 30px;margin-bottom:60px;">
    <img src="{% static 'image/404.png' %}" alt="404 page" class="img img-responsive center-block" />
</div>

{% endif %}

{% endblock %}

main/templates/main/booking-page.html
{% extends 'main/layout.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    label {
        color: rgb(0, 0, 0);
        letter-spacing: 2px;
    }

    .form-control {
        width: 90%;
    }

    .btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(7, 7, 218);
        border-radius: 2rem;
        width: 150px;
        font-weight: 700;
    }

    .btn-primary:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(7, 7, 218);
    }

    .help-block {
        font-size: 16px !important;
    }

    .btn-danger {
        float: left;
        margin-left: -18px;
        margin-top: -10px;
        height: 20px;
        background-color: rgb(7, 7, 218);
        border: none;
    }

    .btn-danger:hover {
        background-color: rgb(122, 122, 241);
    }

    .payment {
        font-weight: 400;
        line-height: 27px;
        letter-spacing: 3px;
        text-align: center;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <div class="container">
                    <label class="btn btn-danger"><input type="checkbox" class="seats" value="1" disabled style="width:0px;"></label>
                <h3 style="position: absolute;margin-top : -10px;margin-left: 30px;"><strong>Booked Seats</strong></h3>
            </div></br></br>

            <div class="seatStructure txt-center" style="overflow-x:auto;">
                <table id="seatsBlock">
                    <tr>
                        {% with range=show.screen.no_of_rows %}
                        {% for i in i|rjust:range %}
                        <td style="padding-left : 25px;">{{ forloop.counter }}</td>
                        {% endfor %}
                        {% endwith %}
                    </tr>
                    {% with range=show.screen.no_of_columns  %}
                    {% for j in j|rjust:range %}
                    <tr>
                        <td style="padding-bottom : 25px;">{{ forloop.counter }}</td>
                        {% with range=show.screen.no_of_rows %}
                        {% for k in k|rjust:range %}
                        <td>{% for t in tickets_booked %}
                            {% if forloop.parentloop.counter == t.row_num and  forloop.parentloop.parentloop.counter == t.col_num %}
                            <label class="btn btn-danger">
                                <input type="checkbox" class="seats" value="{{ forloop.parentloop.counter }}" disabled
                                    style="width:0px;"></label>
                            {% endif %}
                            {% endfor %}
                        </td>
                        {% endfor %}
                        {% endwith %}
                    </tr>
                    {% endfor %}
                    {% endwith %}
                </table></br>
                <div class="jumbotron" style="width:90%;padding : 6px;">
                    <h3 style="margin-left : 40%;color:rgb(7, 7, 218);"><strong>SCREEN</strong></h3>
                </div>

            </div>

        </div>
        <div class="col-lg-6">

            <div class="jumbotron" style="width:90%;">
                <form action="{% url 'main:book-ticket' pk=show.id id=user.id %}" method="POST">
                    {% csrf_token %}
                    {{ form|crispy}}
                    </br><input type="submit" class="btn btn-primary" value="Submit" />
                    </br></br>
                    <h5 class="payment"><strong>NOTE* :</strong> Rs {{ show.price }} will be deducted from your linked
                        wallet</h5>
                </form>
            </div>


        </div>
    </div>
</div>



{% endblock %}

main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Popcorn Time</title>
  <!--External Links-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/w3.css' %}">
  <script src="{%static 'js/bootstrap.min.js' %}"></script>

  <!-- custom style sheet -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

  <link href="https://fonts.googleapis.com/css?family=Bitter" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>


<body style="background-color:rgb(255, 246, 246)">

    <nav class="navbar navbar-inverse navbar-static-top hidden-sm hidden-xs" id="navigation_bar">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'main:index' %}" style="color: rgb(255, 255, 255);"><strong><span
                id="first_letter">P</span>opcorn <span id="first_letter">T</span>ime</strong></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right " style="text-align: center;margin-right : 10px;">
            {% if user.is_authenticated %}
          <li><a href="{% url 'main:accounts' pk=user.id user=user.username %}"><strong>Welcome {{ user.username }}</strong></a></li>
          {% endif %}
          <li><a href="{% url 'main:movies' %}"><strong><span class="glyphicon glyphicon-fire" style="color: red;"></span>&nbsp;
                Movies</strong></a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Logout</strong></a></li>
          {% else %}
          <li><a href="{% url 'main:signup' %}"><strong><span class="glyphicon glyphicon-user"></span>&nbsp;Signup</strong></a></li>
          <li><a href="{% url 'login' %}"><strong><span class="glyphicon glyphicon-log-in"></span>&nbsp; Login</strong></a></li>
          {% endif %}
            <form class="navbar-form navbar-right" action="{% url 'main:search' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Movie,Hero,Heroine" name="search" >
              </div>
              <button type="submit" class="btn btn-default"><strong>Submit</strong></button>
            </form>
          </ul>
        </div>
      </div>
    </nav>
  
  
    <!-- End of navbar -->
  
  
    <!--mobile navbar-->
  
  
    <div class="topnav" id="myTopnav" style="margin-bottom:20px;">
      <div class="hidden-lg hidden-md">
  
        <a href="#"><strong><span id="first_letter">I</span>O Screen</strong></a>
        <a href="#" style="color: rgb(255,255,255);"><i class="far fa-newspaper" style="font-size: 20px;"></i>
          &nbsp;<strong><span id="first_letter">P</span>rojects</strong></a>
        <a href="#" style="color: rgb(255,255,255);"><i class="fab fa-blogger-b" style="font-size: 20px;"></i>
          &nbsp;<strong><span id="first_letter">B</span>log</strong></a>
  
        <form action="">
          <input type="text" class="form-control" placeholder="Search">
          <button type="submit" class="btn btn-primary" id="search_submit" style="margin-top : 10px;">Submit</button>
        </form>
  
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
        </a>
      </div>
    </div>
  
    <script>
      function myFunction() {
        var x = document.getElementById("myTopnav");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
    </script>
  
  
    <!--end of mobile navbar-->


    {% block content %}
    {% endblock %}

    <div class="container-fluid" style="background-color: rgb(0,0,0);padding-top: 40px;">
        <div class="row">
          <div class="col-lg-6" style="text-align: center;">
            <a class="footer-brand" href="#" style="color: rgb(255, 255, 255);"><strong><span
                  id="first_letter">P</span>opcorn <span id="first_letter">T</span>ime</strong></a>
            <h6 class="footer-brand" style="font-size : 16px;"><strong>Spice Up Your Life</strong></h6>
          </div>
          <div class="col-lg-6" style="text-align: center;">
            <a href="#" style="font-size: 30px;padding-right : 30px;color: rgb(255, 255, 255)"> <i
                class="fab fa-github"></i> </a>
            <a href="#" style="font-size: 30px;color: rgb(255, 255, 255);padding-right : 30px;"> <i
                class="fab fa-linkedin"></i> </a>
            <a href="#" style="font-size: 30px;color: rgb(255, 255, 255);padding-right : 30px;"> <i
                class="fab fa-twitter"></i> </a>
            <a href="#" style="font-size: 30px;color: rgb(255, 255, 255)"> <i class="fab fa-facebook"></i> </a>
          </div>
        </div>
        <p style="text-align : center;color : rgb(255,255,255);">&copy; Popcorn Time 2019</p>
      </div>
    
    </body>
    
    </html>

main/templates/main/movie-booking-theatre.html
{% extends 'main/layout.html' %}

{% block content %}

<style>
    .btn-default {
        border: 1px solid rgb(24, 100, 5);
    }

    .slideshow_image {
        box-shadow: 0px 4px 8px 0px rgb(0,0,0);
        border-radius: 20px;
    }
</style>

<div class="container-fluid" style="margin-top: -20px;">
    <img src="{{ movie.slideshow_image.url }}" alt="{{ movie.slideshow_image }}" height="350px;" width="95%"
        class="center-block slideshow_image" />

    <h2 style="text-align: center;color: rgb(0,0,0);margin-top : 20px;"><strong>Confirm Your Show For <span style="color : rgb(255,0,0);">{{ movie.name|upper}}</span> </strong></h2>
</div>

<div class="container" style="margin-bottom: 20px;">
    {% for current in movie.show_movie.all %}
    {% ifchanged %}
    <h4 style="margin-top : 20px;margin-bottom: 20px;"><strong>{{ current.theatre.name }} {{ current.date }}</strong>
    </h4>
    {% endifchanged %}
    <a href="{% url 'main:movie-booking' pk=current.id %}"><button class="btn btn-default" style="display: inline-block;margin-left : 15px;">{{ current.time }}</button></a>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/movie-detail-view.html
{% extends 'main/layout.html' %}

{% block content %}

<style>
    .btn-primary {
        color: rgb(255, 255, 255);
        background-color: rgb(0, 0, 0);
        border-radius: 2rem;
        width: 300px;
        height: 50px;
        font-weight: 700;
        font-size: 20px;
        margin-top: -28px;
        position: absolute;
        left: 38%;
        border: none;
        letter-spacing: 3px;
    }

    .btn-primary:hover ,.btn-custom:hover {
        color: rgb(0, 0, 0);
        background-color: rgb(255, 255, 255);
    }

    .btn-custom {
        color: rgb(255, 255, 255);
        background-color: rgb(0, 0, 0);
        border-radius: 2rem;
        width: 500px;
        height: 50px;
        font-weight: 700;
        font-size: 20px;
        border: none;
        letter-spacing: 3px;
        margin-bottom: 30px;
    }
</style>

<div class="container-fluid" style="margin-top: -40px;">
    <img src="{{ movie.slideshow_image.url }}" alt="{{ movie.slideshow_image }}" height="450px;" width="100%"
        class="center-block" />
    <a href="{% url 'main:movie-booking-theatre' pk=movie.id %}"><button class="btn btn-primary center-block">Book Tickets</button></a>
</div>

<div class="container" style="margin-top : 50px;">
    <div class="row">
        <div class="col-lg-4">
            <img src="{{ movie.thumbnail_image.url }}" alt="{{ movie.thumbnail_image }}" height="300px;" width="80%"
                class="center-block" />
        </div>
        <div class="col-lg-8">
            <iframe width="100%" height="300px" src="https://www.youtube.com/embed/{{movie.trailer}}" frameborder="0"
                class="center-block" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        </div>
    </div>
    <div class="row" style="margin-top : 30px;" >
        <div class="col-lg-4" style="text-align: center;letter-spacing: 3px;padding-top : 25px;">
            <h3 style="color: rgb(255, 0, 0);"><strong>{{ movie.name|upper }}</strong></h3>
            <h5 style="padding: 5px;line-height: 30px !important">{{ movie.language }}</h5>
            <h5 style="padding-bottom: 5px;">{{ movie.genre }}</h5>
            <h4><strong>{{ movie.release_date }} &nbsp;&nbsp; {{ movie.runtime_in_minutes }}</strong></h4>
        </div>
        <div class="col-lg-8" style="margin-bottom: 20px;">
            <p style="letter-spacing : 2px;line-height : 30px;color : rgb(0, 0, 0);;">{{ movie.description }}</p>
        </div>
        <a href="{% url 'main:movie-booking-theatre' pk=movie.id %}"><button class="btn btn-custom center-block">Book Tickets</button></a>
    </div>
</div>


{% endblock %}

main/templates/main/movie-view.html
{% extends 'main/layout.html' %}

{% block content %}

<style>

    .filterDiv {
        display : none;
        float: left;
        margin-bottom : 30px;
        margin-left : 15px;
        width: 200px;
    }

    .show {
        display : inline-block;
    }

    .btn-primary {
        color: rgb(0, 0, 0);
        background-color: rgb(255, 255, 255);
        border-radius: 2rem;
        width: 130px;
        height: 40px;
        font-weight: 700;
        border: 1px solid rgb(0, 0, 0);
        margin-bottom: 15px;
        letter-spacing: 3px;
        font-size: 15px;
    }

    .btn-primary:hover, .btn-primary:focus, .btn-primary:active {
        color: rgb(255, 255, 255) !important;
        background-color: rgb(255, 0, 0) !important;
    }

    button:focus {
        outline: none !important;
    }
</style>

<div class="container-fluid">
    <div class='row'>
        <div class="col-lg-3">
            <div id="myBtnContainer">
                <button class="btn btn-primary" onclick="filterSelection('all')">All</button>
                <h5 style="margin-left: 15px;color: rgb(255, 0, 0)"><strong>GENRE</strong></h5>
                <button class="btn btn-primary" onclick="filterSelection('Drama')"> Drama</button>
                <button class="btn btn-primary" onclick="filterSelection('Romance')"> Romance</button>
                <button class="btn btn-primary" onclick="filterSelection('Action')"> Action</button>
                <button class="btn btn-primary" onclick="filterSelection('Thriller')"> Thriller</button>
                <button class="btn btn-primary" onclick="filterSelection('Family')"> Family</button>
                <h5 style="margin-left: 15px;color: rgb(255, 0, 0)"><strong>LANGUAGE</strong></h5>
                <button class="btn btn-primary" onclick="filterSelection('Kannada')"> Kannada</button>
                <button class="btn btn-primary" onclick="filterSelection('Malyalam')"> Malyalam</button>
                <button class="btn btn-primary" onclick="filterSelection('Hindhi')"> Hindhi</button>
                <button class="btn btn-primary" onclick="filterSelection('Tamil')"> Tamil</button>
                <button class="btn btn-primary" onclick="filterSelection('Telugu')"> Telugu</button>
            </div>
        </div>
        <div class="col-lg-9" style="overflow: hidden;">
            <div class="row">
                {% for image in movie %}
                
                    <div class="card filterDiv {{ image.genre }} {{ image.language }}" >
                        <a href="{% url 'main:movie-detail-view' pk=image.id %}"><img
                                src="{{ image.thumbnail_image.url }}" alt="{{ image.thumbnail_image }}"
                                style="width:100%;height: 300px;border-radius: 10px;"></a>
                    </div>
                
                {% endfor %}
            </div>
        </div>
    </div>
</div>


<script>
    filterSelection("all")

    function filterSelection(c) {
        var x, i;
        x = document.getElementsByClassName("filterDiv");
        if (c == "all") c = "";
        // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
        for (i = 0; i < x.length; i++) {
            w3RemoveClass(x[i], "show");
            if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
        }
    }

    // Show filtered elements
    function w3AddClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            if (arr1.indexOf(arr2[i]) == -1) {
                element.className += " " + arr2[i];
            }
        }
    }

    // Hide elements that are not selected
    function w3RemoveClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            while (arr1.indexOf(arr2[i]) > -1) {
                arr1.splice(arr1.indexOf(arr2[i]), 1);
            }
        }
        element.className = arr1.join(" ");
    }

    
</script>

{% endblock %}